name: CI for releasing tagged versions

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install -e .[dev]
      - name: Build dists for Python 3.7
        run: |
          python setup.py sdist
          python setup.py bdist_wheel
      - name: Publish
        uses: actions/upload-artifact@v2
        with:
          name: Distribution files
          path: dist/
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload source distribution
        id: upload-source-dist-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/garage-door-controller-${{ github.ref }}.tar.gz
          asset_name: garage-door-controller-${{ github.ref }}.tar.gz
          asset_content_type: application/gzip
      - name: Upload wheel distribution
        id: upload-wheel-dist-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/garage-door-controller-${{ github.ref }}-py3-none-any.whl
          asset_name: garage-door-controller-${{ github.ref }}-py3-none-any.whl
          asset_content_type: application/zip

      
      
