name: CI unit tests and style

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install -U pip setuptools
        pip install .[dev]
    - name: Lint with flake8
      run: flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    # - name: Lint with pylint
    #   run: pylint garage_door_controller test
    - name: Test with pytest
      run: |
        pytest
    # - name: Doc style
    #   run: pydocstyle
